version: "3.8"

services:
  ros2_humble:
    build: ./
    image: ros_humble_scara_control
    command: /bin/bash
    tty: true
    privileged: true
    stdin_open: true
    environment:
      DISPLAY: $DISPLAY
    network_mode: "host"
    volumes:  
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - launch_app.sh:/home/ros2_user/ws_ros