version: "3.8"

services:
  ros2_humble:
    build: ./
    image: ros_humble_scara_control
    command: /bin/bash
    tty: true
    privileged: true # Consider security implications of this setting
    stdin_open: true
    environment:
      DISPLAY: $DISPLAY
    network_mode: "host"
    volumes:  
      - ros2_ws:/home/ros2_user/ws_ros
      - ros2_install:/opt/ros
      - /dev:/dev  # Necessary for direct device access, ensure security
      - /tmp/.X11-unix:/tmp/.X11-unix  # For X11 forwarding
      - ./launch_app.sh:/home/ros2_user/ws_ros/launch_app.sh  # Ensure this script is executable
volumes:
  ros2_ws:
    driver: local
  ros2_install:
    driver: local